{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "56404f13",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"Minimal loader for NASCTN CBRS SEA raw dayblock zips.\n",
    "\n",
    "Layout follows NIST TN 2359, Section 3 and Table 4:\n",
    "  dayblock .zip -> many .sigmf (tar) -> .sigmf-meta (JSON) + .sigmf-data (LZMA, float16)\n",
    "  Each sweep has 18 channels x 5560 values, channels centered 3535...3705 MHz.\n",
    "\n",
    "No dependency on sea_ingest, so it works on any recent Python/numpy.\n",
    "\"\"\"\n",
    "import io\n",
    "import json\n",
    "import lzma\n",
    "import tarfile\n",
    "import warnings\n",
    "import zipfile\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "\n",
    "N_CH = 18\n",
    "PER_CH = 5560\n",
    "FREQS_MHZ = 3535 + 10 * np.arange(N_CH)\n",
    "PFP_MS = np.arange(560) * 10 / 560  # PFP bin times within the 10 ms frame\n",
    "\n",
    "# (start, stop_exclusive) inside one channel block, from TN 2359 Table 4\n",
    "SLICES = {\n",
    "    \"psd_max\": (0, 125),\n",
    "    \"psd_mean\": (125, 250),\n",
    "    \"psd_median\": (250, 375),\n",
    "    \"pvt_max\": (1250, 1650),\n",
    "    \"pvt_mean\": (1650, 2050),\n",
    "    \"pfp_peak_min\": (2050, 2610),\n",
    "    \"pfp_peak_max\": (2610, 3170),\n",
    "    \"pfp_peak_mean\": (3170, 3730),\n",
    "    \"pfp_rms_min\": (3730, 4290),\n",
    "    \"pfp_rms_max\": (4290, 4850),\n",
    "    \"pfp_rms_mean\": (4850, 5410),\n",
    "}\n",
    "\n",
    "\n",
    "def _read_sigmf(buf):\n",
    "    \"\"\"Return (metadata dict, float32 array) from one .sigmf tar archive.\"\"\"\n",
    "    meta = data = None\n",
    "    with tarfile.open(fileobj=io.BytesIO(buf)) as tar:\n",
    "        for m in tar.getmembers():\n",
    "            if m.name.endswith(\".sigmf-meta\"):\n",
    "                meta = json.load(tar.extractfile(m))\n",
    "            elif m.name.endswith(\".sigmf-data\"):\n",
    "                data = tar.extractfile(m).read()\n",
    "    if meta is None or data is None:\n",
    "        raise ValueError(\"archive missing .sigmf-meta or .sigmf-data\")\n",
    "    arr = np.frombuffer(lzma.decompress(data), dtype=np.float16).astype(np.float32)\n",
    "    return meta, arr\n",
    "\n",
    "\n",
    "def _freq_mhz(cap, ch):\n",
    "    f = cap.get(\"core:frequency\")\n",
    "    if f is None:\n",
    "        return float(FREQS_MHZ[ch])\n",
    "    return f / 1e6 if f > 1e5 else float(f)  # SigMF stores Hz\n",
    "\n",
    "\n",
    "def load_dayblock(path):\n",
    "    \"\"\"Load one dayblock zip into a DataFrame with one row per (sweep, channel).\"\"\"\n",
    "    records, skipped = [], 0\n",
    "    with zipfile.ZipFile(path) as z:\n",
    "        for name in sorted(z.namelist()):\n",
    "            if not name.endswith(\".sigmf\"):\n",
    "                continue\n",
    "            try:\n",
    "                meta, arr = _read_sigmf(z.read(name))\n",
    "            except Exception as e:  # corrupt or unexpected file\n",
    "                skipped += 1\n",
    "                warnings.warn(f\"{name}: {e}\")\n",
    "                continue\n",
    "            if arr.size != N_CH * PER_CH:\n",
    "                skipped += 1\n",
    "                warnings.warn(f\"{name}: unexpected size {arr.size}\")\n",
    "                continue\n",
    "            caps = meta.get(\"captures\", [])\n",
    "            for ch in range(N_CH):\n",
    "                block = arr[ch * PER_CH:(ch + 1) * PER_CH]\n",
    "                cap = caps[ch] if ch < len(caps) else {}\n",
    "                rec = {\n",
    "                    \"file\": name,\n",
    "                    \"channel\": ch,\n",
    "                    \"freq_mhz\": _freq_mhz(cap, ch),\n",
    "                    \"time\": cap.get(\"core:datetime\"),\n",
    "                    \"overload\": cap.get(\"ntia-sensor:overload\"),\n",
    "                }\n",
    "                for key, (a, b) in SLICES.items():\n",
    "                    rec[key] = block[a:b]\n",
    "                records.append(rec)\n",
    "    df = pd.DataFrame(records)\n",
    "    if not df.empty:\n",
    "        df[\"time\"] = pd.to_datetime(df[\"time\"], utc=True, format=\"mixed\")\n",
    "        df[\"peak_dbm\"] = df[\"pfp_peak_max\"].apply(np.max)\n",
    "        df[\"rms_dbm\"] = df[\"pfp_rms_mean\"].apply(np.mean)\n",
    "        df[\"radar_score\"] = df[\"pfp_peak_max\"].apply(radar_score)\n",
    "    print(f\"{path}: {df['file'].nunique() if not df.empty else 0} sweeps loaded, {skipped} skipped\")\n",
    "    return df\n",
    "\n",
    "\n",
    "def radar_score(pfp_peak_max_dbm):\n",
    "    \"\"\"How strongly the peak PFP repeats every 1 ms (10 times per 10 ms frame).\n",
    "\n",
    "    A bin-1 style pulsed radar (1 ms pulse interval, TN 2359 Sec. 4.4.3) gives a\n",
    "    large score; cellular TDD and thermal noise give scores near 1.\n",
    "    \"\"\"\n",
    "    x = 10 ** (np.asarray(pfp_peak_max_dbm, dtype=float) / 10)\n",
    "    x = x - x.mean()\n",
    "    spec = np.abs(np.fft.rfft(x)) ** 2\n",
    "    harmonic = spec[10]  # 10 cycles per frame = 1 ms period\n",
    "    background = np.median(spec[1:60])\n",
    "    return float(harmonic / background) if background > 0 else np.nan\n",
    "\n",
    "\n",
    "def plot_pfp(row, ax=None):\n",
    "    \"\"\"Plot peak and RMS periodic frame power for one (sweep, channel) row.\"\"\"\n",
    "    import matplotlib.pyplot as plt\n",
    "\n",
    "    ax = ax or plt.gca()\n",
    "    ax.fill_between(PFP_MS, row[\"pfp_peak_min\"], row[\"pfp_peak_max\"], alpha=0.3, color=\"C3\")\n",
    "    ax.plot(PFP_MS, row[\"pfp_peak_mean\"], color=\"C3\", label=\"Peak detect (mean)\")\n",
    "    ax.fill_between(PFP_MS, row[\"pfp_rms_min\"], row[\"pfp_rms_max\"], alpha=0.3, color=\"C0\")\n",
    "    ax.plot(PFP_MS, row[\"pfp_rms_mean\"], color=\"C0\", label=\"RMS detect (mean)\")\n",
    "    ax.set_xlabel(\"Time within 10 ms frame (ms)\")\n",
    "    ax.set_ylabel(\"Channel power (dBm / 10 MHz)\")\n",
    "    ax.set_title(f\"{row['freq_mhz']:.0f} MHz  {row['time']:%Y-%m-%d %H:%M} UTC  overload={row['overload']}\")\n",
    "    ax.legend(loc=\"upper right\")\n",
    "    return ax"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e872cddd",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ds2",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
